name: Update Space News

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fetch Space News
        run: |
          curl -s https://api.spaceflightnewsapi.net/v4/articles/?limit=5 > news.json

          NEWS=$(cat news.json | jq -r '.results[] | "- 🚀 [" + .title + "](" + .url + ")"')

          awk '
          /<!--START_SECTION:space-news-->/ {print; system("echo \"'$NEWS'\""); skip=1; next}
          /<!--END_SECTION:space-news-->/ {skip=0}
          !skip
          ' README.md > temp.md

          mv temp.md README.md

      - name: Commit Changes
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add README.md
          git commit -m "Updated live space news" || exit 0
          git push
